[mgr]
prepend_keymap = [
  { on = ["n"], run = "leave" },  # go back
  { on = ["i"], run = "arrow -1" },
  { on = ["e"], run = "arrow 1" },
  { on = ["o"], run = "enter" }, # regular enter incase a differentiation is needed
  { on = ["<Enter>"], run = "plugin smart-enter" },  # go forward
  { on = ["m"], run = "arrow -5" },
  { on = ["k"], run = "arrow 5" },
  { on = ["N"], run = "back" },  # Go back to the previous directory.
  { on = ["O"], run = "forward" },  # Go forward to the next directory.
  { on = ["<C-u>"], run = "seek -5" },
  { on = ["<C-e>"], run = "seek 5" },
  { on = ["h"], run = "find_arrow" },
  { on = ["H"], run = "find_arrow --previous" },
  { on = ["b", "k"], run = "close" },
  { on = ["t", "k"], run = "close" },

  #' for split tabs'
  { on = "\\", run = [ "plugin split-tabs spl_toggle", "plugin split-tabs spl_preview"], desc = "Split-tabs: toggle split tabs mode" },
  { on = "<Tab>", run = "plugin split-tabs spl_switch_tab", desc = "Split-tabs: switch to the other pane" },
  { on = "<F5>", run = [ "escape --visual", "plugin split-tabs spl_copy" ], desc = "Split-tabs: copy to the other pane" },
  { on = "<F6>", run = [ "escape --visual", "plugin split-tabs spl_move" ], desc = "Split-tabs: move to the other pane" },
  { on = "P", run = "plugin split-tabs spl_preview", desc = "Split-tabs: toggle preview pane" },

  # for the system ctlipboard copy stuff
  { on  = "y", run = [ "yank", 'plugin clipboard-ya -- --action=copy' ], desc = "Yank selected files (copy)"},
  { on  = "x", run = [ "yank --cut", 'plugin clipboard-ya -- --action=copy' ], desc = "Yank selected files (cut)"},
  { on  = "<C-p>", run = [ 'plugin clipboard-ya -- --action=paste' ], desc = "Paste yanked system clipboard files"},

  # drag and drop
  { on   = [ "<C-d>" ], run  = "plugin drag", desc = "Drag Files"},

  # mount
  { on  = "M", run = "plugin mount", desc = "mount stuff"},
]

[tasks]
prepend_keymap = [
  { on = ["W"], run = "close" },
  { on = ["i"], run = "arrow -1" },
  { on = ["e"], run = "arrow 1" },
]

[spot]
prepend_keymap = [
]

[pick]
prepend_keymap = [
]

[input]
prepend_keymap = [
  { on = ["n"], run = "move -1" },  # go back
  { on = ["o"], run = "move 1" }, # regular enter incase a differentiation is needed
  { on = ["t"], run = "insert" },
  { on = ["<C-n>"], run = "move -999" },
  { on = ["<C-o>"], run = "move 999" },
  { on = ["<C-N>"], run = ["move -999", "insert"] },
  { on = ["<C-O>"], run = ["move 999", "insert --append"] },
  { on = ["<A-n>"], run = "move -1" },
  { on = ["<A-o>"], run = "move 1" },
  { on = ["h"], run = "forward --end-of-word" },
  { on = ["x"], run = ["delete", "move 1 --in-operating"] },
  { on = ["u"], run = "undo" },
  { on = ["U"], run = "redo" },
]

[confirm]
prepend_keymap = [
]

[completion]
prepend_keymap = [
  { on = ["<C-i>"], run = "arrow -1" },
  { on = ["<C-e>"], run = "arrow 1" },
]

[help]
prepend_keymap = [
  { on = ["i"], run = "arrow -1" },
  { on = ["e"], run = "arrow 1" },
  { on = ["m"], run = "arrow -5" },
  { on = ["k"], run = "arrow 5" },
]
